### ISSUE TITLE
Update my location :)

### ISSUE THREAD

**Issue by Heeled-Jim** [Mte90/Tech-Speakers-Map#80]
{
      			"name": "Abiel Tomás Parra Hernández", 
      			"url": "https://mozillians.org/en-US/u/quarry.cero/",
      			"gravatar": "abiel.tph@mozilla-mexico.org",
      			"country": "UK",
      			"lat": 53.4039, 
      			"lng": -1.5631
},

**Comment by Mte90** [comment]
This project is obsolete now there is a tool that scrape from mozillians.org https://tchspk.rs/map/
